### ISSUE TITLE
Layout of the commands

### ISSUE THREAD

**Issue by danielbachhuber** [humanmade/wp-remote-cli#1]
We have the potential to have a lot of commands. As such, thinking through how we structure them will be important.

Here's the route I went down to start:

```
remote
    site-list
    site-add
    site-delete
    plugin-list
    plugin-install
```

Here's what we might consider instead:

```
wpr-site
    list
    add
    get
    delete
    refresh

wpr-plugin
    list
    install
    activate
    deactivate
    uninstall
    update
```

Any feedback or suggested alternatives?

**Comment by danielbachhuber** [comment]
cc @joehoyle

**Comment by danielbachhuber** [comment]
... And one more thing to consider: should it be `wpr-plugin` or `wpr-site-plugin`? Technically the latter is correct.

**Comment by willmot** [comment]
What about

```
wp remote
    site
        list
        add
        get
        delete
        refresh
        backup
        setting

    plugin
        list
        install
        activate
        deactivate
        uninstall
        update
        lock
```

I imagine the `plugin` & `theme` commands would require a `--site` arg?

**Comment by joehoyle** [comment]
so, I think for now, we only support listing sites, as the API doesn't support listing plugins or themes for a whole account.

**Comment by danielbachhuber** [comment]
This pattern would be ideal, WP-CLI doesn't easily support sub-sub-commands in this manner at the moment.

> I imagine the plugin & theme commands would require a --site arg?

Generally, we'd just make `<site-id>` the first argument for a `theme` or `plugin` command. There's some prior art for that for the WP-CLI commands I've written in the application itself.

**Comment by joehoyle** [comment]
Oh right, just saw @willmot's comments about the site argument, however, it's not the usual patterns to require a `--site` arg if that arg is required, that's why one would do: `wp remote site 34 list-themes` or whatever

**Comment by willmot** [comment]
> Generally, we'd just make <site-id> 

That makes sense.

So

`wp remote plugin 3765 list`

**Comment by joehoyle** [comment]
I think for the above to make sense, the cli api we are building will only be in scope of managing a site at a time, other wise this will say "list all sites with plugin 3765", more than "list plugins on site 3765", as you don't have the `site` command in there.

We can discuss this later, will probably be easier though.

**Comment by danielbachhuber** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/642#issuecomment-22199641

**Comment by danielbachhuber** [comment]
Will eventually be solved by https://github.com/humanmade/wp-remote-cli/pull/30
